# FROM java:8
# VOLUME /tmp
# ADD springcloud-eureka-server-0.1.jar app.jar
# RUN bash -c 'touch /app.jar'
# EXPOSE 8761
# ENTRYPOINT [ "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar" ]